version: "3.8"

services:
  serverjs:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - express

  express:
    build: ./Backend
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Banksida
    ports:
      - "3306:3306"
